# Default values for rebm-api
replicaCount: 1

image:
  repository: rebm-api
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Application specific configuration
config:
  nodeStoreBackend: "dynamodb"
  nodeStoreTableName: "ReBM-dev"
  
# AWS configuration for DynamoDB
aws:
  region: "us-west-2"
  # Use IAM roles or provide access keys
  # accessKeyId: ""
  # secretAccessKey: "" 